@startuml
'https://plantuml.com/class-diagram

class Core {
    main : Core
    logger : Logger
    fileMan : FileManager
    userManager : UserManager
    economyProvider : EconomyImpl
    vaultHook : VaultHook
    configFile : CustomFile
    lootFile : CustomFile
    copFile : CustomFile
    plugMan : PluginManager
    worldGuardPlugin : WorldGuardPlugin
    worldGuard: WorldGuard
}

class UserManager {

}

class EconomyImpl {
    core : Core
--
    Implemented Economy Methods
}

class VaultHook {
}
@enduml
